### ISSUE TITLE
step scan does not work because of missing `latency_time`

### ISSUE THREAD

**Issue by jkotan** [ALBA-Synchrotron/sardana-redis#2]
Hi @reszelaz  and @ovallcorba,

When I try the recorder with `ascan` I get the following error
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sardana/macroserver/scan/gscan.py", line 596, in _getFileRecorders
    file_recorder = self._rec_manager.getRecorderClass(
  File "/home/jkotan/fsec-sardana/sardana-redis/sardana_redis/recorder/redis_bliss_recorder.py", line 100, in __init__
    sleep_time=macro.latency_time,
  File "/usr/lib/python3/dist-packages/sardana/macroserver/macro.py", line 2568, in __getattr__
    raise AttributeError("%r object has no attribute %r" %
AttributeError: 'ascan' object has no attribute 'latency_time'
```
I would propose  to fix it by e.g.

```patch
diff --git a/sardana_redis/recorder/redis_bliss_recorder.py b/sardana_redis/recorder/redis_bliss_recorder.py
index a344ecf..01100f8 100644
--- a/sardana_redis/recorder/redis_bliss_recorder.py
+++ b/sardana_redis/recorder/redis_bliss_recorder.py
@@ -97,7 +97,7 @@ class RedisBlissRecorder(DataRecorder):
             title=macro.macro_command,
             npoints=macro.nb_points,
             count_time=macro.integ_time,
-            sleep_time=macro.latency_time,
+            sleep_time=(macro.latency_time if hasattr(macro, "latency_time") else None),
             stab_time=None,
             data_policy='no_policy',
             data_writer='nexus',
```

**Comment by ovallcorba** [comment]
Hi @jkotan 
Thanks for testing the recorder! and detecting the latency time issue.
Give me some time and this morning I will update the repo with the latest version of the recorder. This last version I am working on is based on the data_info schema defined blissdata and is compatible with the current versions of blissdata, nexuswriter and flint.
Regards!

**Comment by ovallcorba** [comment]
Hi again,
I updated the code, tomorrow I will try to update the documentation.

**Comment by jkotan** [comment]
thanks.
